# Generated by Django 5.2.4

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in PKR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
